{
    'name': 'Website Ext',
    'version': '17.0.0.0.0',
    'category': 'Website',
    'description': "Module to resdeign website",
    'author': 'Intercraftsol',
    'company': 'Intercraftsol',
    'maintainer': 'Intercraftsol',
    'website': "https://www.Intercraftsol.com",
    'depends': ['base', 'hr', 'website', 'website_hr_recruitment', 'crm', 'website_mass_mailing', 'website_event'],
    'data': [
        'security/ir.model.access.csv',
        'views/team_member_views.xml',
        'views/team_components.xml',
        'views/website_project_views.xml',
        'views/extended_views/header_ext.xml',
        'views/extended_views/s_google_map_ext.xml',
        'views/extended_views/website_form_view_ext.xml',
        'views/extended_views/newletter_ext.xml',
        'views/snippet_home_page.xml',
        'views/contact_us.xml',
        'views/careers.xml',
        'views/privacy_policy.xml',
        'views/terms_conditions.xml',
        'views/side_contact_us.xml',
        'views/our_team.xml',
        'views/about_us.xml',
        'views/thank_you.xml',
        'views/extended_views/footer_ext.xml',
        'views/services/ai_expert.xml',
        'views/services/erp_solution.xml',
        'views/services/koha_ils.xml',
        'views/services/mobile_application.xml',
        'views/services/moodle_lms.xml',
        'views/services/resource_augmentation.xml',
        'views/services/ui_ux.xml',
        'views/services/sqa.xml',
        'views/services/blockchain.xml',
        'views/services/cloud-services.xml',
        'views/services/web_application.xml',
        'views/extended_views/hr_department_ext_view.xml',
        'views/extended_views/job_detail_ext.xml',
        'views/extended_views/hr_applicant_ext.xml',
        'views/extended_views/event_reg_ext.xml',
        'views/extended_views/apply_form_ext.xml',
        'views/extended_views/index_view_ext.xml',
        'views/extended_views/thankyou_ext.xml',
        'data/config_data_ext.xml',
        'views/seo_templates.xml',
        'views/our_work.xml',
        'views/extended_views/account_asset_ext.xml',
        'views/event_image_views.xml',
        'data/event_image_data.xml',
        'views/upcoming_event_views.xml',
        'data/upcoming_event_data.xml',
    ],
    'assets': {
        'web.assets_frontend': [

            # '/website_ext/static/src/js/open_jobs.js',
            '/website_ext/static/src/js/*.js',
            '/website_ext/static/src/css/*.css'
            # '/website_ext/static/src/scss/*.s/css'

        ],
    },
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
